# Generated by Django 5.1 on 2024-08-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('button', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Button',
            new_name='Subscriber',
        ),
    ]
